ALTER TABLE [dbo].[SpecialitySquadDuty]
    ADD CONSTRAINT [PK_SpecialitySquadDuty] PRIMARY KEY CLUSTERED ([Specialities_ID] ASC, [SquadDuties_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

